import puppeteer from "puppeteer-core";
const CHROME = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome";
const b = await puppeteer.launch({ executablePath: CHROME, headless: "new", args:["--no-first-run","--hide-scrollbars"], defaultViewport:{width:1440,height:900,deviceScaleFactor:1}});
const p = await b.newPage();
await p.goto("http://localhost:3000/classic", { waitUntil:"networkidle2", timeout:60000 });
await new Promise(r=>setTimeout(r,1500));
await p.screenshot({ path:"/tmp/kalpana-shots/classic-top.png" });
await p.evaluate(()=>window.scrollTo(0,1750));
await new Promise(r=>setTimeout(r,700));
await p.screenshot({ path:"/tmp/kalpana-shots/classic-mid.png" });
await b.close();
console.log("classic shots done");
