import puppeteer from "puppeteer-core";
const CHROME = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome";
const b = await puppeteer.launch({ executablePath: CHROME, headless:"new", args:["--no-first-run","--hide-scrollbars"], defaultViewport:{width:1440,height:900}});
const p = await b.newPage();
await p.goto("http://localhost:3000/classic",{waitUntil:"networkidle2",timeout:60000});
await new Promise(r=>setTimeout(r,2000));
await p.screenshot({path:"/tmp/kalpana-shots/cl-top.png"});
await p.evaluate(()=>document.getElementById("skills")?.scrollIntoView({block:"start"}));
await new Promise(r=>setTimeout(r,2200));
await p.screenshot({path:"/tmp/kalpana-shots/cl-skills.png"});
await b.close(); console.log("done");
